spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Hn030807
    url: jdbc:postgresql://localhost:5434/realworld
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
application:
  security:
    jwt:
      expiration: 3000000
      secret-key: XNGpES2W4Miuldtn8gFIkfyfgKXDv0m7OIPDNE9BdhpUWd0c755zkr0gR4NgJWuB