package com.neusoft.model;

/**
 * article_tags
 * 
 * @author bianj
 * @version 1.0.0 2025-09-15
 */
public class ArticleTags implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 8828078635956809210L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** articleId */
    private Integer articleId;

    /** tagId */
    private Integer tagId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取articleId
     * 
     * @return articleId
     */
    public Integer getArticleId() {
        return this.articleId;
    }

    /**
     * 设置articleId
     * 
     * @param articleId
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * 获取tagId
     * 
     * @return tagId
     */
    public Integer getTagId() {
        return this.tagId;
    }

    /**
     * 设置tagId
     * 
     * @param tagId
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}