package com.neusoft.model;

import java.sql.Timestamp;

/**
 * articles
 * 
 * @author bianj
 * @version 1.0.0 2025-09-15
 */
public class Articles implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -4877613021949091555L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** slug */
    private String slug;

    /** title */
    private String title;

    /** description */
    private String description;

    /** body */
    private String body;

    /** authorId */
    private Integer authorId;

    /** createdAt */
    private Timestamp createdAt;

    /** updatedAt */
    private Timestamp updatedAt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取slug
     * 
     * @return slug
     */
    public String getSlug() {
        return this.slug;
    }

    /**
     * 设置slug
     * 
     * @param slug
     */
    public void setSlug(String slug) {
        this.slug = slug;
    }

    /**
     * 获取title
     * 
     * @return title
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * 设置title
     * 
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 获取description
     * 
     * @return description
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * 设置description
     * 
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 获取body
     * 
     * @return body
     */
    public String getBody() {
        return this.body;
    }

    /**
     * 设置body
     * 
     * @param body
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * 获取authorId
     * 
     * @return authorId
     */
    public Integer getAuthorId() {
        return this.authorId;
    }

    /**
     * 设置authorId
     * 
     * @param authorId
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 获取updatedAt
     * 
     * @return updatedAt
     */
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * 设置updatedAt
     * 
     * @param updatedAt
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}