package com.neusoft.model;

import java.sql.Timestamp;

/**
 * comments
 * 
 * @author bianj
 * @version 1.0.0 2025-09-15
 */
public class Comments implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -558632812168410387L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** body */
    private String body;

    /** articleId */
    private Integer articleId;

    /** authorId */
    private Integer authorId;

    /** createdAt */
    private Timestamp createdAt;

    /** updatedAt */
    private Timestamp updatedAt;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取body
     * 
     * @return body
     */
    public String getBody() {
        return this.body;
    }

    /**
     * 设置body
     * 
     * @param body
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * 获取articleId
     * 
     * @return articleId
     */
    public Integer getArticleId() {
        return this.articleId;
    }

    /**
     * 设置articleId
     * 
     * @param articleId
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * 获取authorId
     * 
     * @return authorId
     */
    public Integer getAuthorId() {
        return this.authorId;
    }

    /**
     * 设置authorId
     * 
     * @param authorId
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * 获取createdAt
     * 
     * @return createdAt
     */
    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    /**
     * 设置createdAt
     * 
     * @param createdAt
     */
    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * 获取updatedAt
     * 
     * @return updatedAt
     */
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * 设置updatedAt
     * 
     * @param updatedAt
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}