package com.neusoft.model;

/**
 * favorites
 * 
 * @author bianj
 * @version 1.0.0 2025-09-15
 */
public class Favorites implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -9020612357439900664L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** userId */
    private Integer userId;

    /** articleId */
    private Integer articleId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取userId
     * 
     * @return userId
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * 设置userId
     * 
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取articleId
     * 
     * @return articleId
     */
    public Integer getArticleId() {
        return this.articleId;
    }

    /**
     * 设置articleId
     * 
     * @param articleId
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}