package com.neusoft.model;

/**
 * follows
 * 
 * @author bianj
 * @version 1.0.0 2025-09-15
 */
public class Follows implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 1348500114874806494L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** followerId */
    private Integer followerId;

    /** followeeId */
    private Integer followeeId;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取followerId
     * 
     * @return followerId
     */
    public Integer getFollowerId() {
        return this.followerId;
    }

    /**
     * 设置followerId
     * 
     * @param followerId
     */
    public void setFollowerId(Integer followerId) {
        this.followerId = followerId;
    }

    /**
     * 获取followeeId
     * 
     * @return followeeId
     */
    public Integer getFolloweeId() {
        return this.followeeId;
    }

    /**
     * 设置followeeId
     * 
     * @param followeeId
     */
    public void setFolloweeId(Integer followeeId) {
        this.followeeId = followeeId;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}