package com.neusoft.model;

/**
 * tags
 * 
 * @author bianj
 * @version 1.0.0 2025-09-15
 */
public class Tags implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3252992216492641735L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** name */
    private String name;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取name
     * 
     * @return name
     */
    public String getName() {
        return this.name;
    }

    /**
     * 设置name
     * 
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}